# Generated by Django 6.0.6 on 2026-06-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEvaluable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('examen', 'Examen'), ('libreta', 'Corrección de libreta'), ('exposicion', 'Exposición'), ('tarea', 'Tarea'), ('otro', 'Otro')], max_length=20)),
                ('modo', models.CharField(choices=[('global', 'Global'), ('por_pregunta', 'Por pregunta')], max_length=15)),
                ('fecha', models.DateField()),
                ('criterios', models.ManyToManyField(blank=True, related_name='actividades_globales', to='curriculo.criterioevaluacion')),
            ],
            options={
                'verbose_name': 'actividad evaluable',
                'verbose_name_plural': 'actividades evaluables',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('puntuacion_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluacion.actividadevaluable')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='curriculo.criterioevaluacion')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['actividad', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('1', '1er Trimestre'), ('2', '2º Trimestre'), ('3', '3er Trimestre'), ('G', 'Global')], max_length=1)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='grupos.asignatura')),
            ],
            options={
                'verbose_name': 'trimestre',
                'verbose_name_plural': 'trimestres',
                'unique_together': {('nombre', 'asignatura')},
            },
        ),
        migrations.AddField(
            model_name='actividadevaluable',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='evaluacion.trimestre'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion', models.CharField(choices=[('numerica', 'Numérica'), ('rubrica', 'Rúbrica')], max_length=10)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nivel_rubrica', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=4)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='evaluacion.actividadevaluable')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='grupos.alumno')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='curriculo.criterioevaluacion')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='evaluacion.trimestre')),
            ],
            options={
                'verbose_name': 'calificación',
                'verbose_name_plural': 'calificaciones',
                'unique_together': {('alumno', 'actividad', 'criterio', 'trimestre')},
            },
        ),
    ]
