# Generated by Django 6.0.6 on 2026-06-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_niveles', models.PositiveSmallIntegerField(default=4)),
                ('criterio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrica_config', to='curriculo.criterioevaluacion')),
            ],
            options={
                'verbose_name': 'configuración de rúbrica',
                'verbose_name_plural': 'configuraciones de rúbrica',
            },
        ),
        migrations.CreateModel(
            name='RubricaNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField()),
                ('valor_numerico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rubrica_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='evaluacion.rubricaconfig')),
            ],
            options={
                'verbose_name': 'nivel de rúbrica',
                'verbose_name_plural': 'niveles de rúbrica',
                'ordering': ['rubrica_config', 'nivel'],
                'unique_together': {('rubrica_config', 'nivel')},
            },
        ),
    ]
