# Generated by Django 6.0.6 on 2026-06-05 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_rubricaconfig_rubricanivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadDidactica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='evaluacion.trimestre')),
            ],
            options={
                'verbose_name': 'unidad didáctica / situación de aprendizaje',
                'verbose_name_plural': 'unidades didácticas / situaciones de aprendizaje',
                'ordering': ['trimestre', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='actividadevaluable',
            name='unidad_didactica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='evaluacion.unidaddidactica'),
        ),
    ]
