# Generated by Django 6.0.6 on 2026-06-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_clave', to='grupos.asignatura')),
            ],
            options={
                'verbose_name': 'competencia clave',
                'verbose_name_plural': 'competencias clave',
                'unique_together': {('codigo', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='CompetenciaEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('competencia_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_especificas', to='curriculo.competenciaclave')),
            ],
            options={
                'verbose_name': 'competencia específica',
                'verbose_name_plural': 'competencias específicas',
                'unique_together': {('codigo', 'competencia_clave')},
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('competencia_especifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='curriculo.competenciaespecifica')),
            ],
            options={
                'verbose_name': 'criterio de evaluación',
                'verbose_name_plural': 'criterios de evaluación',
                'unique_together': {('codigo', 'competencia_especifica')},
            },
        ),
    ]
